name: clickTwitch

on: 
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
